vmware: Add option for setting default hw_version
sapcc/nova pull request #171
Opened 2020-12-07 14:53 UTC by joker-official

This is necessary with multi-version clusters where migrating e.g. on
resize needs to be possible.

Change-Id: Idc287c4dfa2b5d6a6a837a5014063417c8e13768

2020-12-07 18:51 UTC, grandchild requested changes
Otherwise LGTM

2020-12-08 07:15 UTC, joker-official commented on nova/conf/vmware.py
> +get upgrade individually but movement of VMs is necessary between them
Thanks.

2020-12-08 08:26 UTC, grandchild approved these changes

2020-12-08 09:12 UTC, GlaciErrDev commented
LGTM

2020-12-08 09:13 UTC, GlaciErrDev reviewed
LGTM

2020-12-08 09:13 UTC, GlaciErrDev approved these changes

2020-12-08 10:19 UTC, merged