vmware: Add Forward-syslog-to-Loginsight config
sapcc/nova pull request #193
Opened 2021-03-25 15:04 UTC by grandchild

After the instance is deleted in VSphere its syslogs are deleted along with it, which hinders post-mortem debugging.

Add a config flag `forward_instance_logs_to_loginsight` to forward all instance logs to VMware's Loginsight monitoring service, to be able to inspect them after the instance is gone.

2021-03-25 15:20 UTC, joker-at-work requested changes
>  its syslogs
better: its "vmware.log" files

2021-03-25 15:20 UTC, joker-at-work commented on nova/conf/vmware.py
> +    cfg.BoolOpt('forward_instance_logs_to_loginsight',
I'd name it `mirror_instance_logs_to_syslog`, because loginsight is just  a backend receiving the syslog of the host

2021-03-25 15:20 UTC, joker-at-work commented on nova/virt/vmwareapi/vm_util.py
> +    # NOTE jakobk: Adapted from
`NOTE` format is usually `# NOTE(<user>): ` in Nova as I see it.

2021-03-25 15:20 UTC, joker-at-work commented on nova/virt/vmwareapi/vm_util.py
> +    # le-to-send-messages-to-vrealize-log-insight.html
I'd rather put this into the commit-message, tbh.

2021-03-25 15:53 UTC, grandchild commented
Done

2021-03-26 08:04 UTC, joker-at-work approved these changes

2021-03-26 09:45 UTC, grandchild commented
Reworded the config help text wording to match the other changes.

2021-03-26 09:46 UTC, merged