Remove tenant filter for Security group search in  VM creation to be able to use shared Security Groups.
sapcc/nova pull request #246
Opened 2021-09-17 13:07 UTC by velp

2021-09-17 14:10 UTC, joker-at-work requested changes
What prohibits a user to specify a non-shared security-group belonging to another project?

2021-09-17 14:12 UTC, joker-at-work commented
There's no explanation of the implication whatsoever in the commit-message. Please explain how this doesn't lower the security of the whole process and why it's necessary to do it like that.

2021-09-20 04:51 UTC, joker-at-work commented
I'd also like to get information about the performance aspect. How much does it cost to list all security groups known to Neutron.

2021-09-22 09:20 UTC, joker-at-work commented
Could you please amend your commit-message to include what you checked and the outcome in a shorter form, so we can find it again in a year or two?

2021-09-22 09:42 UTC, velp commented
@joker-at-work ofc, I will do it with squash commit when merging

2021-09-22 10:22 UTC, joker-at-work commented
... and nobody sees the commit-message until you merged.

2021-09-23 09:55 UTC, velp commented
I think we should agree on a single merge method and use it. Now I do not know which method I should use specifically in this repository when I creating PR, there is no documentation or description in the CONTRIBUTORS file which flow we are using. I think it's better to discuss this outside the scope of the fix that our colleagues are waiting for, so I just made one commit with the full description as you want.

2021-09-28 12:47 UTC, joker-at-work approved these changes
There don't seem to be other callers of these functions with admin tokens or therelike, so that it should be safe to remove the filters.

2021-09-28 12:47 UTC, merged