vmware: Apply NUMA flavor recommendations
sapcc/nova pull request #387
Opened 2022-11-30 17:30 UTC by grandchild

Physical CPUs are faster than hyperthreaded CPUs. So by default VMware spreads a VM's CPU cores onto physical cores, spanning multiple NUMA nodes if needed although the vCPUs would fit onto a smaller number of NUMA nodes.

HANA VMs prefer low-latency (and thus NUMA-locality) over raw performance, so they set the VMware config `preferHT` to not get spread out. Before this setting was only applied if the VM's flavor qualified as a "Big VM" flavor (i.e. >1GiB) in size. This excluded smaller HANA flavors and a single-NUMA-node VM got spread over two nodes.

Make `preferHT` depend on whether the flavor requires one of our `CUSTOM_NUMASIZE_*` traits instead.

2022-12-09 13:38 UTC, joker-at-work approved these changes

2023-01-26 10:09 UTC, joker-at-work requested changes
There are 2 other places where we call `disable_drs_if_needed()` which should probably also call `set_restart_priority_if_needed()` then:
```
nova/virt/vmwareapi/driver.py:1038:            self._vmops.disable_drs_if_needed(instance)
nova/virt/vmwareapi/vmops.py:1492:        self.disable_drs_if_needed(instance)
nova/virt/vmwareapi/vmops.py:1499:    def disable_drs_if_needed(self, instance):
nova/virt/vmwareapi/vmops.py:2675:        self.disable_drs_if_needed(instance)
```

Do we have to unset `numa_vcpu_max_per_virtual_node` again on resize to a smaller VM or does it not matter if that is set on smaller VMs?

2023-01-26 11:27 UTC, grandchild commented
> There are 2 other places where we call `disable_drs_if_needed()` which should probably also call `set_restart_priority_if_needed()`

done

> Do we have to unset numa_vcpu_max_per_virtual_node again on resize to a smaller VM

this does happen. like `prefer_ht` and `migration_data_timeout` setting `numa_vcpu_max_per_virtual_core` to the empty string if not numa-aligned-flavor should remove the setting.

2023-01-26 11:30 UTC, joker-at-work commented
> > Do we have to unset `numa_vcpu_max_per_virtual_node` again on resize to a smaller VM
> 
> this does happen. like `prefer_ht` and `migration_data_timeout`, setting `numa_vcpu_max_per_virtual_core` to the empty string if not numa-aligned-flavor should remove the setting.

Ah, because we call `_get_extra_specs()` everywhere (basically) and don't really use the default of the `ExtraSpecs` object. I see.

2023-01-31 10:26 UTC, joker-at-work approved these changes

2023-01-31 10:43 UTC, merged