SAP: add get_scheduler_settings admin API
sapcc/nova pull request #484
Opened 2024-03-08 15:32 UTC by leust

Change-Id: I88a9b36de44ddd967c1acb5d542f7c105d6a4e42

2024-04-22 13:08 UTC, joker-at-work requested changes

2024-04-22 13:08 UTC, joker-at-work commented on nova/api/openstack/compute/sap_admin_api.py
> +        """
Please update the docstring to match the contents.

2024-04-22 13:08 UTC, joker-at-work commented on nova/api/openstack/compute/sap_admin_api.py
> +    def _get_scheduler_settings(self):
What's the point of splitting this functionality off into another method?

2024-04-22 13:08 UTC, joker-at-work commented on nova/api/openstack/compute/sap_admin_api.py
> +        context.can(sap_policies.POLICY_ROOT % 'get-scheduler-settings')
We have to add that to `nova.policies.sap_admin_api`.

2024-06-12 12:55 UTC, joker-at-work approved these changes

2024-06-13 07:35 UTC, fwiesel approved these changes

2024-06-13 08:32 UTC, merged