vmware: handle the ToolsUnavailableException on power_off
sapcc/nova pull request #496
Opened 2024-05-27 09:05 UTC by leust

Even though Nova checks if the VM has VMware tools running, this exception might still occur if the VMware tools stop running in the meantime.

We return False back, so that Nova continues to hard shutdown.

Change-Id: Ida4d6dfd2dab0ad0a382f7c98b69c8326414bdda

2024-06-03 14:06 UTC, joker-at-work requested changes

2024-06-03 14:06 UTC, joker-at-work commented on nova/virt/vmwareapi/vmops.py
> +                LOG.exception("Failed to _clean_shutdown the instance")
I don't think this should be an exception. We handle it gracefully, so there should imho be at max a warning, I'd even use "INFO" for this.

I think we have to pass `instance=instance` here, so we actually know "the instance"?

2024-06-05 10:50 UTC, joker-at-work approved these changes

2024-06-05 11:01 UTC, fwiesel approved these changes

2024-06-05 11:03 UTC, merged