Hack: libvirt: Support maxphysaddr.
sapcc/nova pull request #512
Opened 2024-09-18 12:17 UTC by fwiesel

This is a hacky version of libvirt: Support maxphysaddr, which does it properly over flavor and images,
but needs also a trait upgrade.

Do not port it to later versions.

With Libvirt v8.7.0+, the <maxphysaddr> sub-element of the <cpu> element specifies the number of vCPU
physical address bits [1].

[1] https://libvirt.org/news.html#v8-7-0-2022-09-01

Change-Id: If89f71511c050a494657614b789adcdb80297725

2024-09-24 12:01 UTC, grandchild requested changes
I don't think we need the `super(MyClass, self)` anymore in python3.

Also, one doc typo.

2024-09-24 12:02 UTC, grandchild commented
Oh, and while you're at it, the commit message has really weird line breaks...

2024-09-25 07:37 UTC, fwiesel commented on nova/conf/workarounds.py
> +This is a hack: Pass simply the maxphyaddr from the host to the VM.
Fixed it.

2024-09-25 07:38 UTC, fwiesel commented
> I don't think we need the super(MyClass, self) anymore in python3.

That's how it has been done [upstream](https://github.com/openstack/nova/commit/1038a633870b24b2409205cc3c5fe066442dd49f#diff-df62e2f09a4fcaddde995d2654d868aa2f72d1ef0fee74b32191c31088aacaabR796-R800). I'd like to avoid deviating from it, as little as possible in case there are more backports needed.

2024-09-25 09:23 UTC, grandchild approved these changes

2024-09-25 10:31 UTC, merged